// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_error from "./routes/_error.tsx";
import * as $about from "./routes/about.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $experience from "./routes/experience.tsx";
import * as $index from "./routes/index.tsx";
import * as $ExperienceTimeline from "./islands/ExperienceTimeline.tsx";
import * as $ProgressBar from "./islands/ProgressBar.tsx";
import * as $TechnicalExpertiseCarousel from "./islands/TechnicalExpertiseCarousel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_error.tsx": $_error,
    "./routes/about.tsx": $about,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/experience.tsx": $experience,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ExperienceTimeline.tsx": $ExperienceTimeline,
    "./islands/ProgressBar.tsx": $ProgressBar,
    "./islands/TechnicalExpertiseCarousel.tsx": $TechnicalExpertiseCarousel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
