// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/auth/github.ts";
import * as $4 from "./routes/blog/[slug].tsx";
import * as $5 from "./routes/changelog.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/posts.tsx";
import * as $$0 from "./islands/Changelog.tsx";
import * as $$1 from "./islands/CommentIsland.tsx";
import * as $$2 from "./islands/PostSearch.tsx";
import * as $$3 from "./islands/ProgressBar.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/auth/github.ts": $3,
    "./routes/blog/[slug].tsx": $4,
    "./routes/changelog.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/posts.tsx": $7,
  },
  islands: {
    "./islands/Changelog.tsx": $$0,
    "./islands/CommentIsland.tsx": $$1,
    "./islands/PostSearch.tsx": $$2,
    "./islands/ProgressBar.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
