import { Handlers, PageProps } from '$fresh/server.ts';
import { CSS, render } from '$gfm';
import { getPostBySlug, Post } from '@utils/posts.ts';
import 'https://esm.sh/prismjs/components/prism-json?no-check';
import 'https://esm.sh/prismjs/components/prism-jsx?no-check';
import 'https://esm.sh/prismjs/components/prism-tsx?no-check';
import 'https://esm.sh/prismjs/components/prism-typescript?no-check';
import 'https://esm.sh/prismjs/components/prism-javascript?no-check';
import 'https://esm.sh/prismjs/components/prism-css?no-check';
import 'https://esm.sh/prismjs/components/prism-markdown?no-check';
import 'https://esm.sh/prismjs/components/prism-bash?no-check';
import 'https://esm.sh/prismjs@1.29.0/components/prism-typescript?no-check';

import { Wrapper } from '../../components/Wrapper.tsx';
import { Disclaimer } from "../../components/Disclaimer.tsx";
import { Tag } from '../../components/Tag.tsx';

export const handler: Handlers<Post> = {
  async GET(_req, ctx) {
    const post = await getPostBySlug(ctx.params.slug);
    if (post === null) return ctx.renderNotFound();
    return ctx.render(post);
  },
};

export default function PostPage(props: PageProps<Post>) {
  const post = props.data;

  return (
    <Wrapper
      title={post.title}
      meta={{
        keywords: post.tags,
        description: post.snippet,
        url: `https://gmaltez.dev/blog/${post.slug}`,
      }}
      head={
        <>
          <style dangerouslySetInnerHTML={{ __html: CSS }} />
          <style>
            {`
              .markdown-body h1,h2,h3,h4,h5,h6 {
                color: #d0d4de;
              }
  
              .markdown-body p {
                color: #d0d4de;
                opacity: 0.9;
              }
              
              .markdown-body .highlight pre {
                background-color: #262c39;
                border-radius: 0.5rem;
              }
            `}
          </style>
        </>
      }
    >
      <Disclaimer
        title="⚠️ Post Generated By AI ⚠️"
        content="Hey! Remember that this blog is still under development, this is
        a fake post generated by AI. The information here may not be accurate, 
        and it's being used only for testing purposes. Thanks for accessing during 
        this early stage :)"
      />
      <h1 className="text-2xl sm:text-4xl font-bold">{post.title}</h1>
      <div className="-my-3 flex flex-row flex-wrap">
        {post.tags.map(tag => <Tag tag={tag} />)}
      </div>
      <hr className="border-text-tertiary border-opacity-50" />
      <div className="flex flex-row items-center justify-start gap-2 min-w-max">
        <img
          height="50"
          width="50"
          className="rounded-full"
          alt="Picture of the author (Gustavo Maltez)"
          src="https://github.com/gustavomaltez.png"
        />
        <div className="flex flex-col">
          <p className="text-1xl">Gustavo Maltez</p>
          <span className="flex flex-row items-center justify-center gap-2 text-text-secondary">
            {Intl.DateTimeFormat('en-US', {
              year: 'numeric',
              month: 'short',
              day: 'numeric',
            }).format(post.publishedAt)}
            <div className="rounded-full h-1 w-1 bg-text-secondary" />
            {post.estimatedReadingTime} min read
          </span>
        </div>
      </div>
      <div
        data-color-mode="dark"
        data-dark-theme="dark"
        class="markdown-body bg-background"
        dangerouslySetInnerHTML={{ __html: render(post.content) }}
        style={{
          backgroundColor: 'transparent',
        }}
      />
    </Wrapper>
  );
}