import { Handlers, PageProps } from '$fresh/server.ts';
import { CSS, render } from '$gfm';
import { getPostBySlug, Post } from '@utils/posts.ts';
import 'https://esm.sh/prismjs/components/prism-json?no-check';
import 'https://esm.sh/prismjs/components/prism-jsx?no-check';
import 'https://esm.sh/prismjs/components/prism-tsx?no-check';
import 'https://esm.sh/prismjs/components/prism-typescript?no-check';
import 'https://esm.sh/prismjs/components/prism-javascript?no-check';
import 'https://esm.sh/prismjs/components/prism-css?no-check';
import 'https://esm.sh/prismjs/components/prism-markdown?no-check';
import 'https://esm.sh/prismjs/components/prism-bash?no-check';
import 'https://esm.sh/prismjs@1.29.0/components/prism-typescript?no-check';

import { Wrapper } from '../../components/Wrapper.tsx';

export const handler: Handlers<Post> = {
  async GET(_req, ctx) {
    const post = await getPostBySlug(ctx.params.slug);
    if (post === null) return ctx.renderNotFound();
    return ctx.render(post);
  },
};

export default function PostPage(props: PageProps<Post>) {
  const post = props.data;

  return (
    <Wrapper
      title={post.title}
      meta={{
        keywords: post.tags,
        description: post.snippet,
        url: `https://gmaltez.dev/blog/${post.slug}`,
      }}
      head={
        <>
          <style dangerouslySetInnerHTML={{ __html: CSS }} />
          <style>
            {`
              .markdown-body h1,h2,h3,h4,h5,h6 {
                color: #c9d4dc;
              }
  
              .markdown-body p {
                color: #a6b0c3;
              }
              
              .markdown-body .highlight pre {
                background-color: #1e2028;
                border-radius: 0.5rem;
              }
            `}
          </style>
        </>
      }
    >
      <Disclaimer />
      <div
        data-color-mode="dark"
        data-dark-theme="dark"
        class="markdown-body bg-background"
        dangerouslySetInnerHTML={{ __html: render(post.content) }}
        style={{
          backgroundColor: 'transparent',
        }}
      />
    </Wrapper>
  );
}

function Disclaimer() {
  return (
    <div className="border-[#ff3b6b] bg-[#4b2f36] border p-4 shadow flex flex-col rounded-xl my-1 mt-3">
      <h2 className="text-2xl font-bold text-[#ff3b6b] mb-2">⚠️ Post Generated By AI ⚠️</h2>
      <p className="text-[#d997b1]">
        Hey! Remember that this blog is still under development, this is a fake post generated by AI.
        The information here may not be accurate, and it's being used only for testing purposes. Thanks
        for accessing during this early stage :)
      </p>
    </div>
  );
}